version: "3.7"

services:
  nginx:
    image: nginx:1.21.4
    networks:
      - network
    volumes:
      - /home/django-course/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static
      - media-volume:/data/media
    ports:
      - 80:80
      - 443:443
  django_containter:
    image: .
    networks:
      - network
    volumes:
      - static-volume:/home/Koterest/staticfiles
      - media-volume:/home/Koterest/media
  mariadb:
    image: mariadb:10.7.1
    networks:
      - network
    volumes:
      - maria-database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:


networks:
  network:

volumes:
  static-volume:
  media-volume:
  maria-database:

